### ISSUE TITLE
404 after inactivity on /reports/

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter_dashboard#170]
After a period of inactivity (i.e. access token has probably expired), if I go directly to the /reports/ page, I get a 404. If I instead go to /sites/ first, /reports/ works fine. I think this is related to how we get the token in api_interface/reports.py. Other interfaces, like sites, use the oauth_request_session which automatically requests a new access token if the current one is expired. I don't think 
```python
token = oauth_request_session.token['access_token'] 
```
does that. Probably need to check if the token is expired, and refresh if it is like https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#first-define-try-catch-tokenexpirederror-on-each-request

**Comment by alorenzo175** [comment]
Actually, what probably makes the most sense (so that tokens are handled properly including stored) is to make a factory function for core.io.api.APISession where we can give it the OAuth2Session and still have the methods like list_reports etc.

**Comment by lboeman** [comment]
This issue seems restricted to the dashboard, and a possibly introduces breaking change in core. Unless there's a benefit to having a token auto refresh feature in core, maybe the dashboard's report interface should be updated to work the same as the others (using oauth_request_session). Then it can load a data model object from the response where necessary?
